'use client';
import {useState,useEffect,useCallback} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import evidence from '../research/evidence.json';
import Opening,{openingTitles} from './opening';
const originalTitles=['AI in sociological research','Complete cognitive offloading','Guided collaboration','The pain-in-the-ass coauthor','The research question','Running a literature-review skill','Inspecting the evidence','Working through an argument','Source and methods review','The research proposal'];
const imageIntro=[{title:'Coxon',src:'/artifacts/opening-images/coxon.jpeg',background:'#000'},{title:'Amodei',src:'/artifacts/opening-images/amodei.png',background:'#fff'},{title:'Trump',src:'/artifacts/opening-images/trump.jpeg',background:'#fff'}];
const titles=[originalTitles[0],...imageIntro.map(x=>x.title),...openingTitles,...originalTitles.slice(1)];
const modes=[{title:originalTitles[1],description:'Give it a bounded task and inspect what comes back.',prompt:'Reproduce this figure from the supplied data. Document any discrepancies.',uses:'Bibliographic records, file conversion, replication checks.',failure:'Accepting the output because it looks finished.'},{title:originalTitles[2],description:'Let it do much of the work; intervene where a decision matters.',prompt:'Show me the proposed measures before running the analysis.',uses:'Developing an analysis, revising a coding scheme, comparing operationalizations.',failure:'Approving each step without really examining it.'},{title:originalTitles[3],description:'You explain an argument. It raises objections. You respond and work through the implications together.',prompt:'I think these findings support displacement. Here is why. What am I missing?',uses:'Theory, measurement, identification and interpretation.',failure:'Treating its objections as authoritative, or accepting agreement as validation.'}];
const exchanges=[['I think chatbots may displace friends because they are always available and easier to approach.','That is a plausible mechanism. But people who already have less support might also use the chatbot more. What would count as displacement: fewer requests, fewer responses, or weaker ties?'],['Fewer requests. Could we compare the share of support needs that lead to a friend?','What if the chatbot changes what people report as a need? Then the denominator changes too. Could total requests over a fixed follow-up be the primary outcome?'],['I also want to know whether suggesting human contact helps people reach out.','We can compare that feature with a standard chatbot offer. That estimates the feature’s effect, not the overall effect of chatbot availability. Let’s keep those questions separate in the protocol.']];
type Modal=null|'evidence'|'cli'|'reviews'|'files'|'contents'|'notes';
function Out({href,children}:{href:string,children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>}
function TextFile({path}:{path:string}){const [text,setText]=useState('Loading…');useEffect(()=>{const c=new AbortController();setText('Loading…');fetch(path,{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.text()}).then(setText).catch(e=>{if(e.name!=='AbortError')setText('Could not load this file. Use the direct link below.');});return()=>c.abort()},[path]);return <><pre className="terminal-output">{text}</pre><Out href={path}>Open original file</Out></>}
export default function Page(){
 const [localMode,setLocalMode]=useState(false);
 const [position,setSlide]=useState(0),[modal,setModal]=useState<Modal>(null),[step,setStep]=useState(0),[exchange,setExchange]=useState(0),[cli,setCli]=useState('setup'),[review,setReview]=useState('source');
 const go=useCallback((n:number)=>setSlide(Math.max(0,Math.min(titles.length-1,n))),[]);
 useEffect(()=>{setLocalMode(['localhost','127.0.0.1'].includes(location.hostname));const sync=()=>{const n=Number(location.hash.slice(1));if(n>=1&&n<=titles.length)setSlide(n-1)};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{history.replaceState(null,'','#'+(position+1))},[position]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(modal||document.querySelector('[role="dialog"]')||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName)||(position>=3&&(e.target as HTMLElement).tagName==='BUTTON'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(position+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(position-1)}if(e.key==='Home')go(0);if(e.key==='End')go(titles.length-1);if(e.key.toLowerCase()==='n')setModal('notes');if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.().catch(()=>{})};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[position,modal,go]);
 const contentPosition=position===0?0:position<=3?-1:position-imageIntro.length;
 const slide=contentPosition===0?0:contentPosition>=5?contentPosition-4:-1;
 const openCli=(v:string)=>{setCli(v);setModal('cli')};
 return <main className="presentation"><header><span>Christopher Barrie and Bart Bonikowski <span className="muted">/ NYU Sociology</span></span><div><Out href="/artifacts/presentation.pdf">PDF slides</Out><button className="quiet" onClick={()=>setModal('files')}>Research files</button></div></header><section className={'scene scene-'+slide+(position>=1&&position<=3?' image-scene':'')} aria-label={'Slide '+(position+1)+': '+titles[position]}>
 {position>=1&&position<=3&&<div className="image-frame" style={{background:imageIntro[position-1].background}}><img src={imageIntro[position-1].src} alt={imageIntro[position-1].title+" opening image"}/></div>}
 {contentPosition>=1&&contentPosition<=4&&<Opening index={contentPosition-1}/>}
 {slide===0&&<div className="cover"><p className="section-label">Faculty discussion · September 2026</p><h1>AI in sociological<br/>research</h1><p className="lead">Some ways we can use these tools<br/>in our own projects.</p><div className="cover-context"><p>Last year: student responses and essays.</p><p>Today: searching, checking, revising and producing research.</p></div><button onClick={()=>go(1)}>Begin presentation →</button></div>}
 {slide>=1&&slide<=3&&<><p className="section-label">Ways of working · {slide} of 3</p><h2>{modes[slide-1].title}</h2><div className="two-col mode"><div><p className="lead">{modes[slide-1].description}</p><h3>Research uses</h3><p>{modes[slide-1].uses}</p><h3>Where it goes wrong</h3><p className="muted">{modes[slide-1].failure}</p></div><div className="prompt-sheet"><span className="file-label">What I might say</span><blockquote>“{modes[slide-1].prompt}”</blockquote>{slide===3&&<p>This is an ongoing conversation. The project changes through the exchange.</p>}</div></div></>}
 {slide===4&&<><p className="section-label">A question to work on</p><h2>Do AI chatbots reduce support-seeking<br/>from friends and family?</h2><div className="two-col article-layout"><div className="article-clipping"><span>The Guardian</span><img src="/artifacts/article-headline.png" alt="Heavy ChatGPT users tend to be more lonely, suggests research"/><p>Rachel Hall · 25 March 2025</p><Out href="https://www.theguardian.com/technology/2025/mar/25/heavy-chatgpt-users-tend-to-be-more-lonely-suggests-research">Open the reporting</Out></div><div><p className="lead">We’ll use this question to work<br/>through an agent-assisted literature review.</p><p>The agent can find papers, compare their findings, check citations and write a synthesis.</p><p className="muted">We can steer the search, question its interpretation and ask it to revise the work.</p></div></div></>}
 {slide===5&&<><p className="section-label">Practical walkthrough</p><h2>Running a literature-review skill</h2><div className="step-tabs" role="group" aria-label="Workflow steps">{['1. Add the skill','2. Give the assignment','3. Inspect the files'].map((x,i)=><button key={x} className={step===i?'active':''} onClick={()=>setStep(i)}>{x}</button>)}</div><div className="two-col workflow"><div>{step===0?<><p className="lead">A skill is a readable instruction file<br/>stored in the research project.</p><p>This one was written for the workshop. Open it and inspect what it asks the agent to check.</p><div className="actions"><Out href="/artifacts/SKILL.md">Read the skill</Out><Out href="/artifacts/literature-audit.zip">Download</Out></div></>:step===1?<><p className="lead">Name the outcome and the outputs.<br/>Tell it where you want to intervene.</p><p>Ask for separate source and methods reviewers when useful. Have them retain their disagreements and questions.</p></>:<><p className="lead">Then open the files it produced.</p><p>The search record, table and bibliography let us inspect the work. The original review predates this reusable skill.</p><button onClick={()=>setModal('evidence')}>Inspect the formatted evidence table</button></>}<p className="small"><Out href="/workshop/howto.html">Full setup instructions and official documentation</Out></p></div><div className="terminal-card"><div className="terminal-bar">{step===0?'Project folder':step===1?'Prompt to enter':'Research outputs'}</div><pre>{step===0?'research-project/\n  .agents/skills/       # Codex\n    literature-audit/\n      SKILL.md\n\n  .claude/skills/       # Claude Code\n    literature-audit/\n      SKILL.md':step===1?'Codex CLI / IDE:\n$literature-audit\n\nClaude Code:\n/literature-audit\n\nFind primary studies on support requests\nto friends and family. Check instruments\nand source versions. Write evidence.csv\nand references.bib. Ask me about\nconsequential ambiguities.':'research/\n  evidence.csv\n  search-log.md\n  references.bib\n  retrieval-manifest.json\n  audit/\n    source-audit.md\n    methods-audit.md'}</pre><button onClick={()=>openCli(step===2?'retrieval':'setup')}>{step===2?'Open recorded retrieval':'Open CLI walkthrough'} ↗</button></div></div></>}
 {slide===6&&<><p className="section-label">Literature search and source checking</p><h2>Inspect the evidence, not just the summary</h2><div className="mini-table"><table><thead><tr><th>Study</th><th>What was compared?</th><th>What was measured?</th></tr></thead><tbody>{evidence.slice(0,3).map(e=><tr key={e.key}><td>{e.short} ({e.year})</td><td>{e.design}</td><td>{e.outcome}</td></tr>)}</tbody></table></div><div className="actions"><button onClick={()=>setModal('evidence')}>Open all nine records</button><button onClick={()=>openCli('retrieval')}>Show retrieval record</button><Out href="https://arxiv.org/html/2503.17473v2">Open Fang et al., v2</Out></div><p className="takeaway">Fang randomized modes and topics. Voluntary use intensity was not randomized, and the socialization measure is not a direct request count.</p></>}
 {slide===7&&<><p className="section-label">Paired intellectual work</p><h2>Working through the argument</h2><div className="dialogue"><div><span>Researcher</span><p>{exchanges[exchange][0]}</p></div><div><span>AI coauthor</span><p>{exchanges[exchange][1]}</p></div></div><div className="actions"><button disabled={exchange===0} onClick={()=>setExchange(exchange-1)}>← Previous exchange</button><button disabled={exchange===2} onClick={()=>setExchange(exchange+1)}>Continue the conversation →</button><Out href="/workshop/coauthor.html">Full exchange</Out></div><p className="small">Scripted teaching example. These are illustrative researcher turns, not a transcript of Christopher’s statements.</p></>}
 {slide===8&&<><p className="section-label">Actual separate-agent review</p><h2>Let the reviewers question each other</h2><div className="two-col reviewers"><div><h3>Source reviewer</h3><p>What did the paper randomize?<br/>Which instrument did it use?<br/>Does the passage support our claim?</p><button onClick={()=>{setReview('source');setModal('reviews')}}>Open source review</button></div><div><h3>Methods reviewer</h3><p>What effect would the study identify?<br/>Are we conditioning on a consequence?<br/>What does the researcher need to decide?</p><button onClick={()=>{setReview('methods');setModal('reviews')}}>Open methods review</button></div></div><p className="takeaway">Both flagged the need-episode denominator. The source reviewer also challenged whether a feature effect identifies a bridging mechanism.</p><p className="small">These reports and cross-checks are actual agent output. Agreement among agents is not empirical validation.</p></>}
 {slide===9&&<><p className="section-label">Research production</p><h2>Open the resulting proposal</h2><div className="two-col memo-layout"><div><p className="lead">A study protocol with an evidence assessment,<br/>estimands and a draft diary instrument.</p><p>The revised question survives into the outcome definition, assignment scheme and analysis.</p><div className="actions"><Out href="/artifacts/study-protocol.pdf">Open PDF normally</Out><Out href="/artifacts/study-protocol.tex">LaTeX</Out><Out href="/artifacts/references.bib">Bibliography</Out></div><p className="small">Four pages plus references. A proposal, not a completed experiment. The instrument is unvalidated.</p></div><a className="memo-preview" href="/artifacts/study-protocol.pdf" target="_blank" rel="noreferrer"><img src="/artifacts/protocol-preview.png" alt="First page of the actual compiled study proposal"/></a></div></>}

 </section><footer><button className="quiet" onClick={()=>setModal('contents')}>{String(position+1).padStart(2,'0')} / {titles.length} <span className="footer-title">{titles[position]}</span></button><div><button className="quiet" onClick={()=>setModal('notes')}>Notes <kbd>N</kbd></button><button className="quiet" onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})}>Fullscreen</button><button disabled={position===0} onClick={()=>go(position-1)} aria-label="Previous slide">←</button><button disabled={position===titles.length-1} onClick={()=>go(position+1)} aria-label="Next slide">→</button></div></footer>
 <Dialog open={modal!==null} onOpenChange={o=>{if(!o)setModal(null)}}><DialogContent className="research-dialog"><DialogTitle>{modal==='evidence'?'Evidence table':modal==='cli'?'CLI walkthrough and execution record':modal==='reviews'?'Actual reviewer output':modal==='contents'?'Presentation contents':modal==='notes'?'Presenter notes':'Research files'}</DialogTitle><DialogDescription>{modal==='cli'?'Setup examples are illustrated; the retrieval video contains real recorded command output.':modal==='reviews'?'Separate source and methods agents, including their cross-checks.':'NYU Sociology faculty presentation'}</DialogDescription>
 {modal==='contents'&&<div className="contents-list">{titles.map((t,i)=><button key={t} onClick={()=>{go(i);setModal(null)}}><span>{i+1}</span>{t}</button>)}</div>}
 {modal==='files'&&<div className="files-list">{[['Opening research and source checks','/workshop/opening.html'],['Study protocol (PDF)','/artifacts/study-protocol.pdf'],['Evidence table','/workshop/evidence.html'],['Skill and setup instructions','/workshop/howto.html'],['Source and methods reviews','/workshop/reviews.html'],['Paired coauthor dialogue (scripted)','/workshop/coauthor.html'],['LaTeX source','/artifacts/study-protocol.tex'],['BibTeX bibliography','/artifacts/references.bib'],['PDF slides','/artifacts/presentation.pdf'],['Complete research archive','/artifacts/research-package.zip'],['Offline presentation','/artifacts/local-presentation.zip']].filter(([,u])=>!localMode||!u.endsWith('local-presentation.zip')).map(([t,u])=><Out key={u} href={u}>{t}</Out>)}</div>}
 {modal==='notes'&&<TextFile path="/artifacts/speaker-notes.md"/>}
 {modal==='evidence'&&<div className="evidence-scroll"><table><thead><tr><th>Study and access</th><th>Design and outcome</th><th>Finding</th><th>Interpretation limit</th></tr></thead><tbody>{evidence.map(e=><tr key={e.key}><td><Out href={e.url}>{e.short} ({e.year})</Out><small>{e.status}<br/>{e.access}</small></td><td>{e.design}<small>{e.outcome}</small></td><td>{e.finding}</td><td>{e.limit}<small>{e.locator}</small></td></tr>)}</tbody></table><Out href="/artifacts/evidence.csv">Open CSV</Out></div>}
 {modal==='cli'&&<><div className="step-tabs"><button className={cli==='setup'?'active':''} onClick={()=>setCli('setup')}>Setup and prompt</button><button className={cli==='retrieval'?'active':''} onClick={()=>setCli('retrieval')}>Actual retrieval</button><button className={cli==='skill'?'active':''} onClick={()=>setCli('skill')}>Skill file</button></div>{cli==='setup'?<><pre className="terminal-output">{'# Illustrated commands — not a captured session\n# From the research project folder:\n\n# Codex CLI / IDE\nmkdir -p .agents/skills\n# Put the downloaded literature-audit folder there\n# Start Codex, then enter:\n$literature-audit\n\n# Claude Code alternative\nmkdir -p .claude/skills\n# Put the same skill folder there\nclaude\n/literature-audit\n\nAssess studies of support requests to friends/family.\nCheck outcome instruments, versions and access limits.\nWrite evidence.csv, search-log.md and references.bib.\nAsk me about consequential ambiguities.'}</pre><p className="small">A fresh session recording is still unavailable: local Claude authentication expired; the installed Codex CLI executable was missing. This is a usable setup example, not a recording of successful execution.</p></>:cli==='retrieval'?<><video controls playsInline src="/artifacts/sources.mp4"/><p className="small">Actual source-retrieval command output. Playback timing adjusted for legibility. The original full review was prepared before this reusable skill.</p><Out href="/artifacts/recordings.zip">Original timestamped logs</Out></>:<TextFile path="/artifacts/SKILL.md"/>}</>}
 {modal==='reviews'&&<><div className="step-tabs"><button className={review==='source'?'active':''} onClick={()=>setReview('source')}>Source reviewer</button><button className={review==='methods'?'active':''} onClick={()=>setReview('methods')}>Methods reviewer</button></div><TextFile path={'/artifacts/'+review+'-audit.md'}/></>}
 </DialogContent></Dialog></main>
}
