import json,csv,pathlib
rows=[
 dict(key='fang2025',author='Fang, Cathy Mengying and Liu, Auren R. and Danry, Valdemar and Lee, Eunhae and Chan, Samantha W. T. and Pataranutaporn, Pat and Maes, Pattie and Phang, Jason and Lampe, Michael and Ahmad, Lama and Agarwal, Sandhini',short='Fang et al.',year=2025,title='How AI and Human Behaviors Shape Psychosocial Effects of Extended Chatbot Use: A Longitudinal Randomized Controlled Study',url='https://arxiv.org/html/2503.17473v2',doi='10.48550/arXiv.2503.17473',venue='arXiv preprint, version 2',status='Preprint; v2, 2 October 2025',access='Full text',design='Four-week randomized comparison of chatbot modes and topics; n=981',outcome='Loneliness, socialization, dependence, problematic use',finding='Revised abstract reports no significant assigned-condition effects; heavier voluntary use is associated with worse outcomes.',limit='Usage intensity was not randomized; socialization is not a count of requests to friends.',locator='Abstract; Results; experimental design',role='Adjacent causal evidence'),
 dict(key='guingrich2025',author='Guingrich, Rose E. and Graziano, Michael S. A.',short='Guingrich & Graziano',year=2025,title='A Longitudinal Randomized Control Study of Companion Chatbot Use: Anthropomorphism and Its Mediating Role on Social Impacts',url='https://arxiv.org/html/2509.19515v3',doi='10.48550/arXiv.2509.19515',venue='arXiv preprint, version 3',status='Preprint; v3, 13 October 2025',access='Full text',design='21-day randomized chatbot versus word-game comparison; n=183',outcome='Social health, loneliness, perceived relationship impacts',finding='No overall significant condition differences; perceived impacts vary with anthropomorphism.',limit='Perceived impact is not observed outreach; magnitude and direction of impact differ.',locator='Methods: Social Impact; Results; Appendix A',role='Adjacent causal evidence'),
 dict(key='chandra2025',author='Chandra, Mohit and Hernandez, Javier and Ramos, Gonzalo and Ershadi, Mahsa and Bhattacharjee, Ananya and Amores, Judith and Okoli, Ebele and Paradiso, Ann and Warreth, Shahed and Suh, Jina',short='Chandra et al.',year=2025,title='Longitudinal Study on Social and Emotional Use of AI Conversational Agent',url='https://arxiv.org/html/2504.14112v1',doi='10.48550/arXiv.2504.14112',venue='arXiv preprint',status='Preprint; v1, April 2025',access='Full text',design='Five-week exploratory active-use versus usual-use groups; n=149',outcome='Attachment, perceived empathy, comfort seeking AI support',finding='Active users reported increased attachment and greater comfort seeking support from AI.',limit='AI comfort does not establish reduced human outreach; recruitment and retention limit inference.',locator='Methods 2.1; Results 3.1.5; Limitations 4.4',role='Mechanism context'),
 dict(key='defreitas2025',author='De Freitas, Julian and O{\\u{g}}uz-U{\\u{g}}uralp, Zeliha and U{\\u{g}}uralp, Ahmet Kaan and Puntoni, Stefano',short='De Freitas et al.',year=2025,title='AI Companions Reduce Loneliness',url='https://www.hbs.edu/ris/Publication%20Files/AI%20Companions%20Reduce%20Loneliness%2011.7.2025_57451c02-8047-4e0d-abfc-55841f64166d.pdf',doi='10.1093/jcr/ucaf040',venue='Journal of Consumer Research',status='Published; advance access 2025, issue 2026',access='Full text, author-hosted published version',design='Multi-study paper: reviews, experiments, one-week longitudinal study',outcome='Momentary loneliness and feeling heard',finding='Chatbot interactions can reduce momentary loneliness; this does not establish lasting relief between interactions.',limit='Loneliness relief and substitution of human requests are distinct outcomes.',locator='Studies 2–5; General Discussion, author PDF p.19',role='Outcome distinction'),
 dict(key='meng2021',author='Meng, Jingbo and Dai, Yue Nancy',short='Meng & Dai',year=2021,title='Emotional Support from AI Chatbots: Should a Supportive Partner Self-Disclose or Not?',url='https://scholars.cityu.edu.hk/en/publications/emotional-support-from-ai-chatbots-should-a-supportive-partner-se/',doi='10.1093/jcmc/zmab005',venue='Journal of Computer-Mediated Communication',status='Published; 26(4), 207–222',access='Institutional abstract and metadata; PDF retrieval failed',design='Online experiment varying source, support, and self-disclosure',outcome='Stress and worry reduction; perceived supportiveness',finding='Support effects depend on the partner and reciprocal self-disclosure.',limit='Immediate distress relief does not measure later contact with friends.',locator='Institutional abstract; methods not independently inspected',role='Mechanism context'),
 dict(key='meng2025',author='Meng, Jingbo and Zhang, Renwen and Qin, Jiaqi and Lee, Yu-Jen and Lee, Yi-Chieh',short='Meng et al.',year=2025,title='AI-mediated social support: the prospect of human--AI collaboration',url='https://academic.oup.com/jcmc/article/30/4/zmaf013/8200809',doi='10.1093/jcmc/zmaf013',venue='Journal of Computer-Mediated Communication',status='Published; 30(4), zmaf013',access='Full text',design='Study of human/AI support-message production and evaluation',outcome='Message features, helpfulness, authenticity',finding='Patterns of human–AI collaboration are associated with different message features and evaluations.',limit='Support provision is not the same as a seeker contacting an existing friend.',locator='Abstract; process-adoption model; Discussion',role='Bridging context, not a bridging estimate'),
 dict(key='young2024',author='Young, Jordyn and Jawara, Laala M. and Nguyen, Diep N. and Daly, Brian and Huh-Yoo, Jina and Razi, Afsaneh',short='Young et al.',year=2024,title='The Role of AI in Peer Support for Young People: A Study of Preferences for Human- and AI-Generated Responses',url='https://arxiv.org/html/2405.02711v1',doi='10.48550/arXiv.2405.02711',venue='arXiv manuscript',status='arXiv version reviewed; venue status not independently verified',access='Full text',design='Survey evaluating blinded support responses; n=622',outcome='Response preferences, helpfulness, willingness to send',finding='Evaluations differ by response source and topic; AI responses were preferred for several topics.',limit='Rating supplied messages does not show subsequent human support-seeking.',locator='Methods 3.2; Results 4.1',role='Outcome distinction'),
 dict(key='skjuve2021',author='Skjuve, Marita and F{\\o}lstad, Asbj{\\o}rn and Fostervold, Knut Inge and Brandtz{\\ae}g, Petter Bae',short='Skjuve et al.',year=2021,title='My Chatbot Companion -- a Study of Human-Chatbot Relationships',url='https://www.sintef.no/en/publications/publication/0198cc8570c8-9e3222db-61c3-4a0e-a6a5-115f3f7b1a33/',doi='10.1016/j.ijhcs.2021.102601',venue='International Journal of Human-Computer Studies',status='Published; 149, 102601',access='Institutional abstract and metadata; full-text redirect unavailable',design='Interviews with 18 people who developed Replika friendships',outcome='Relationship development and perceived social consequences',finding='Participants described valued chatbot relationships and mixed wider social effects.',limit='Selected users and retrospective accounts do not identify a population causal effect.',locator='Institutional abstract',role='Qualitative mechanism context'),
 dict(key='ueda2026',author='Ueda, Michiko and Birnbaum, Michael L. and Liu, Yanhong and Yu, Qingyi and Tian, Xihe and Mirer, Anna and Ramanathan, Seethalakshmi and Sinyor, Mark',short='Ueda et al.',year=2026,title='Help-Seeking in the Age of AI: Cross-Sectional Survey of the Use and Perceptions of AI-Based Mental Health Support Among US Adults',url='https://mental.jmir.org/2026/1/e88196/',doi='10.2196/88196',venue='JMIR Mental Health',status='Published; 2026, e88196',access='Full text',design='Cross-sectional survey of US adults; n=1805',outcome='Use and attitudes toward AI and professional support',finding='AI users held more favorable attitudes to AI support; attitudes toward human counselors did not vary by AI-use status.',limit='Professional help is outside the primary outcome; attitudes and associations are not behavioral effects.',locator='Results: attitudes; Discussion',role='Boundary case; excluded from informal-support synthesis')]
p=pathlib.Path('research');(p/'evidence.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False))
with (p/'evidence.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
with (p/'references.bib').open('w') as f:
 for r in rows:
  f.write('@article{'+r['key']+',\n'+''.join(f'  {k} = {{{v}}},\n' for k,v in {'author':r['author'],'title':r['title'],'year':r['year'],'journal':r['venue'],'doi':r['doi'],'url':r['url'],'note':r['status']+'; accessed 8 September 2026'}.items())+'}\n\n')
print('Saved 9 evidence records: 8 core/context studies + 1 professional-support boundary case.')
