from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from pathlib import Path
import json
P=Path('public/artifacts'); W,H=1280,720
for n,f in [('Sans','Arial.ttf'),('Bold','Arial Bold.ttf'),('Serif','Georgia.ttf')]:pdfmetrics.registerFont(TTFont(n,'/System/Library/Fonts/Supplemental/'+f))
C=canvas.Canvas(str(P/'presentation.pdf'),pagesize=(W,H));C.setTitle('AI in sociological research');C.setAuthor('Christopher Barrie and Bart Bonikowski')
base='https://nyu-sociology-ai-research.chrisjbarrie.chatgpt.site'
notes=[]
slide_number=0
def text(x,y,s,size=23,font='Sans',color='#222222'):
 C.setFont(font,size);C.setFillColor(HexColor(color));C.drawString(x,H-y,s)
def para(x,y,s,width=1090,size=27,font='Sans'):
 p=Paragraph(s,ParagraphStyle('p',fontName=font,fontSize=size,leading=size*1.4,textColor=HexColor('#222222')));pw,ph=p.wrap(width,H);p.drawOn(C,x,H-y-ph);return ph

def frame(i,title):
 global slide_number
 slide_number+=1
 i=slide_number
 C.setFillColor(HexColor('#f8f6f1'));C.rect(0,0,W,H,fill=1,stroke=0)
 text(70,45,'Christopher Barrie and Bart Bonikowski · NYU Sociology',16,color='#555555');text(1130,45,str(i)+'/17',16,color='#555555')
 C.setStrokeColor(HexColor('#cccccc'));C.line(70,H-66,1210,H-66)
 text(70,135,title,40,'Serif');C.setStrokeColor(HexColor('#8c72a6'));C.setLineWidth(2);C.line(70,H-157,160,H-157);C.setLineWidth(1)
def link(x,y,label,path,size=21):
 url=path if path.startswith('https://') else base+path
 text(x,y,label,size,color='#493280');w=pdfmetrics.stringWidth(label,'Sans',size);C.line(x,H-y-3,x+w,H-y-3);C.linkURL(url,(x,H-y-9,x+w,H-y+size),relative=0)
def bullets(items,start=205,size=27,gap=99):
 for j,t in enumerate(items):para(70,start+j*gap,'• '+t,1125,size)
def end(note):C.showPage();notes.append(note)
frame(1,'AI in sociological research');para(70,235,'Some ways I think we can use these tools<br/>in our own research',1110,38,'Serif');para(70,385,'Last year’s discussion focused on student responses and essays.<br/>Today I want to look at what happens inside a research project.',1110,27);link(70,605,'Open the demonstration files','/');end('0:00–1:00. Explain the change in focus from student writing to research. Do not make a model benchmark claim. The practical difference in this example is that the agent can search, inspect files, revise several related outputs and run software in one project. The browser deck is the primary presentation. Arrow keys navigate; use the slide buttons for evidence tables, CLI examples and actual records. Keep the PDF as backup.')
# Opening images retain the deck frame and the complete supplied screenshot.
from PIL import Image
for filename,color in [('coxon.jpeg','#000000'),('amodei.png','#ffffff'),('trump.jpeg','#ffffff')]:
 slide_number+=1
 C.setFillColor(HexColor('#f8f6f1'));C.rect(0,0,W,H,fill=1,stroke=0)
 text(70,45,'Christopher Barrie and Bart Bonikowski · NYU Sociology',16,color='#555555');text(1130,45,str(slide_number)+'/17',16,color='#555555')
 C.setStrokeColor(HexColor('#cccccc'));C.line(70,H-66,1210,H-66)
 path=P/'opening-images'/filename
 iw,ih=Image.open(path).size;scale=min(1136/iw,556/ih);dw,dh=iw*scale,ih*scale
 C.setFillColor(HexColor(color));C.setStrokeColor(HexColor('#cfc3de'));C.roundRect(70,55,1140,560,8,fill=1,stroke=1)
 C.drawImage(str(path),70+(1140-dw)/2,55+(560-dh)/2,width=dw,height=dh,mask='auto')
 end('Opening aside: '+filename.split('.')[0].title()+'. User-supplied image within the presentation frame, without added claims or captions.')
def paper_shot(x,y,w,h,key,url):
 from PIL import Image
 path='public/artifacts/study-screenshots/'+key+'.png'
 iw,ih=Image.open(path).size;scale=min((w-24)/iw,(h-20)/ih);dw,dh=iw*scale,ih*scale
 C.setFillColor(HexColor('#ffffff'));C.setStrokeColor(HexColor('#d5cedb'));C.roundRect(x,H-y-h,w,h,4,fill=1,stroke=1)
 C.drawImage(path,x+(w-dw)/2,H-y-(h+dh)/2,width=dw,height=dh,mask='auto');C.linkURL(url,(x,H-y-h,x+w,H-y),relative=0)
frame(0,'Cognitive offloading and learning');para(70,181,'External resources change what we need to remember and do ourselves.',1120,23)
for x,key,url,title,kind,body in [(70,'risko','https://samgilbert.net/pubs/Risko2016TiCS.pdf','Risko & Gilbert','2016 · Review','Offloading reduces cognitive demands. Consequences depend on the task and use of the aid.'),(455,'lee','https://doi.org/10.1145/3706598.3713778','Lee et al.','2025 · Workplace survey','319 workers: confidence in AI was associated with less reported critical thinking.'),(840,'bastani',base+'/artifacts/bastani-pnas.pdf','Bastani et al.','2025 · Randomized school trial','Unaided exam grades fell after unrestricted AI practice help. A guided tutor largely removed the penalty.')]:
 paper_shot(x,230,345,170,key,url);text(x,430,kind,16,color='#6c567b');text(x,469,title,27,'Serif');para(x,490,body,345,21)
para(70,626,'Reduced effort, reduced learning and lasting cognitive loss are different claims.',1130,23,'Serif');link(70,682,'Actual paper excerpts · click a screenshot to open its source','/workshop/opening.html',17)
end('Discuss the evidence by design. Lee measures reported effort; Bastani measures subsequent unaided mathematics performance. Neither is a longitudinal study of faculty cognitive decline. Risko and Gilbert provide the broader offloading framework. Sparrow and the EEG preprint are in the readings for discussion, rather than the core slide.')
frame(0,'What research agents can accomplish');paper_shot(70,193,530,200,'coscientist','https://www.nature.com/articles/s41586-026-10644-y.pdf');paper_shot(670,193,530,200,'crux','https://arxiv.org/pdf/2607.27191');text(70,428,'Google · Nature, 2026',17,color='#6c567b');text(670,428,'Kirgis et al., including Narayanan · 2026 preprint',16,color='#6c567b');text(70,470,'Co-Scientist',29,'Serif');text(670,470,'Two open-ended research tasks',28,'Serif');para(70,491,'Agents proposed hypotheses; scientists selected and tested them in the lab.',530,23);para(670,491,'Six days of research: engineering completed, but both papers judged below the publication bar.',530,23);para(70,601,'A system can extend what a researcher can execute while still needing their judgment.',1130,24,'Serif');link(70,658,'METR: what a time horizon measures','https://metr.org/time-horizons/',17);text(70,689,'Actual paper excerpts · selected studies, not a head-to-head comparison.',16,color='#555555')
end('These are different evaluations, not a head-to-head comparison. Co-Scientist includes expert selection and laboratory validation. The two CRUX cases show a gap between execution and research judgment; do not universalize two cases. METR reports benchmark task durations in human-time units, not autonomous scientific runtime. This evidence concerns what systems can do; the preceding slide concerns effects on people.')
frame(0,'2025: the chat window');C.setFillColor(HexColor('#fffdf9'));C.roundRect(70,H-570,620,370,12,fill=1,stroke=0);text(94,235,'Illustrated exchange',16,color='#756184');C.setFillColor(HexColor('#ede6f3'));C.roundRect(170,H-355,490,95,8,fill=1,stroke=0);para(190,276,'Summarize research on chatbots and support-seeking from friends and family.',450,23);para(94,400,'A prose response appears here, with suggested themes and references to inspect.',545,24);text(94,539,'Ask a follow-up…',19,color='#756184');text(755,248,'The researcher carries the workflow',25,'Serif');para(755,296,'Read the answer.<br/>Find the papers.<br/>Move material into files.<br/>Run analysis elsewhere.',450,26);para(70,619,'The use case discussed last year. Tool-using and multi-agent systems already existed in 2025.',1120,20);end('Use this as a reminder of last year’s session, not a literal history of product capabilities. The exchange is illustrated. Chat can also be intellectually collaborative, and it remains useful. The new point is that execution can now happen inside the same research environment.')
frame(0,'2026: working with a team of agents')
def box(x,y,w,label,sub,fill='#fffdf9'):
 C.setFillColor(HexColor(fill));C.setStrokeColor(HexColor('#bca9ca'));C.roundRect(x,H-y-70,w,70,6,fill=1,stroke=1);text(x+14,y+29,label,21,'Serif');text(x+14,y+53,sub,14,color='#6d5a79')
C.setFillColor(HexColor('#efebf3'));C.roundRect(275,H-570,660,370,10,fill=1,stroke=0);text(295,226,'AGENT HARNESS · tools, state, context and handoffs',15,color='#6c567b')
C.setStrokeColor(HexColor('#a58daf'));C.setLineWidth(1.5)
for x1,y1,x2,y2 in [(230,353,252,353),(252,353,252,289),(252,289,490,289),(710,289,1000,289),(1000,289,1000,353),(1000,353,1015,353),(600,325,600,345),(385,345,810,345),(385,345,385,363),(810,345,810,363),(600,345,600,363),(470,398,510,398),(685,398,725,398),(385,433,385,469),(600,433,600,485),(810,433,810,469),(385,469,810,469)]:C.line(x1,H-y1,x2,H-y2)
box(70,318,160,'Researcher','Question + judgment');box(490,254,220,'Coordinator','Plans and delegates','#e1d3ed');box(295,363,175,'Literature','Retrieve + verify');box(510,363,175,'Analysis','Code + write');box(725,363,190,'Review','Challenge + check');box(345,485,515,'Shared workspace and progress record','Papers, results, decisions and unfinished tasks','#e1d3ed');box(1015,318,190,'Research files','Data · code · PDF');para(70,603,'The harness manages execution around the model. The researcher remains part of the revision loop.',1120,22);link(70,658,'Open the four-stage interactive diagram','/#8',18);text(630,658,'Teaching schematic; no agents are running on the slide.',17,color='#555555');end('In the browser, click the stages: assignment, parallel work, cross-checking, revision. Explain harness once as the software around the model that handles tools, state and execution. Saved project files allow continuation beyond one conversation window. This schematic combines common architectural patterns; it is not a faithful diagram of one vendor product. Agent agreement still needs source and substantive checks.')
frame(2,'1. Complete cognitive offloading');bullets(['Give it a bounded task and inspect what comes back.','“Reproduce this figure from the supplied data and document any discrepancies.”','Other uses: bibliographic records, file conversion, replication checks.'],gap=105);para(70,558,'The failure is accepting an output because it looks finished.',1100,24);end('1:00–2:00. Here the researcher specifies a task with a checkable result. Execution can be delegated, but responsibility for the result remains with us. An example is reproducing a figure: compare data, axes, values and exclusions, rather than just seeing that an image appeared. This is one working relationship, not the lowest rung of a hierarchy.')
frame(3,'2. Guided collaboration');bullets(['Let it do much of the work; intervene where a decision matters.','“Show me the proposed measures before running the analysis.”','Other uses: developing an analysis, revising a coding scheme, comparing operationalizations.'],gap=105);para(70,566,'The failure is approving each step without really examining it.',1100,24);end('2:00–3:00. The point is to put review at a consequential choice. Asking to see measures before analysis is useful; asking it to report every trivial step is usually not. We can give reasons for a change and have it follow the implications through code, tables and writing. We should inspect the revised result, not just the acknowledgement.')
frame(4,'3. The pain-in-the-ass coauthor');para(70,205,'You bring an argument. It questions it. You respond, and work through the implications together.',1100,30);para(70,342,'“I think these findings support displacement. Here is why.<br/>What am I missing?”',1100,28);para(70,480,'Useful for theory, measurement, identification and interpretation.<br/>Its objections need scrutiny too; it can misunderstand the evidence.',1100,25);end('3:00–4:00. This is a paired intellectual relationship, not outsourcing a referee report. You explain your interpretation; it raises a problem; you answer; the project changes through the exchange. The third mode describes an intellectual role, while the first two emphasize delegation. We can move among all three during the same project. AI objections can be wrong, and agreement is not a validation test.')
frame(5,'Do chatbots change how people seek support?');C.drawImage(str(P/'article-headline.png'),70,H-310,width=1060,height=142.4375,mask='auto');text(70,347,'Rachel Hall, The Guardian, 25 March 2025',19,color='#555555');para(70,402,'Our question: do AI chatbots reduce requests for support<br/>from friends and family?',1110,31);para(70,493,'An agent can find papers, compare findings, check citations and write a synthesis.',1110,23);link(70,577,'Open the article','https://www.theguardian.com/technology/2025/mar/25/heavy-chatgpt-users-tend-to-be-more-lonely-suggests-research');end('4:00–5:00. The headline is a cropped screenshot of the actual article. Use this question to introduce what an agent-assisted research workflow can do: find papers, compare findings, check citations and write a synthesis. We steer the search, question its interpretation and ask it to revise. This slide introduces the demonstration, not a full research design. Open the article briefly if useful, then move to the research folder.')
frame(6,'What would you actually type?');para(70,195,'Open a project folder, add the skill, then give it the question.',1120,27);text(70,286,'Codex CLI / IDE:  $literature-audit',25);text(70,331,'Claude Code:       /literature-audit',25);text(70,369,'Header example: allowed-tools: Read WebSearch Bash(pdftotext *)',18,color='#6c567b');para(70,390,'“Find primary studies. Check the outcome instruments and source versions. Write an evidence table and bibliography. Ask me about consequential ambiguities.”',1110,27);text(70,530,'Agent → Python script → Literature database → Records to inspect',21,color='#6c567b');text(70,558,'Illustrative workflow; no script execution is claimed.',15,color='#555555');link(70,586,'Open the skill and setup instructions','/workshop/howto.html');text(70,637,'Workshop-authored skill; search and file tools depend on the session.',17,color='#555555');end('5:00–6:15. Open the how-to page. Click SKILL.md and show that it is a readable instruction file. Explain the project paths: .agents/skills in Codex, .claude/skills in Claude Code. Show the exact invocation and prompt. Click Run a script to explain the illustrative workflow: an agent calls Python, the script queries a literature API and saves records, then the agent reads and checks the returned material. The command is a teaching example; that script is not included or claimed to have run. The skill codifies the original workflow; do not imply the original review was produced by a recorded run of this skill. The local Claude login expired and the Codex CLI binary was unavailable, so no authentic skill-invocation clip is included. Official setup links are on the page. Keep this explanation practical.')
frame(7,'What the literature search produced');para(70,199,'Nine study records, a search log and a bibliography.<br/>Each record retains the design, measures, findings and source version.',1120,27)
for j,(a,b) in enumerate([('Study design','What was assigned, and what was self-selected?'),('Outcome','Requests, socialization, loneliness, or response ratings?'),('Source check','Which version? Full text or abstract only?')]):text(70,328+76*j,a,23,'Bold');text(360,328+76*j,b,23)
link(70,602,'Open evidence table','/workshop/evidence.html');link(365,602,'Open retrieval record','/artifacts/retrieval-manifest.json');link(690,602,'Open bibliography','/artifacts/references.bib');end('Show the products of the 8 September search: nine evidence records, retrieval log and bibliography. Each table record links to its primary source and names the source version and access limits. Fang v2 remains accessible through its record, rather than a disconnected slide-level link. The later source review shows what was checked and corrected. These outputs fed the proposal compiled on 9 September; the reusable skill codifies this earlier workflow.')
frame(8,'Working through a measurement decision');text(70,205,'RESEARCHER',16,'Bold', '#555555');para(70,225,'“Could we compare the share of support needs that lead to a friend?”',1120,29);text(70,355,'AI COAUTHOR',16,'Bold','#555555');para(70,375,'“What if chatbot use changes what people report as a need?<br/>Then the denominator changes too. Could total requests over<br/>a fixed follow-up be the primary outcome?”',1120,28);link(70,604,'Open the full exchange','/workshop/coauthor.html');text(70,649,'Scripted teaching example; the actual reviewer reports are linked separately.',17,color='#555555');end('8:00–9:30. Open the scripted exchange. Read two or three turns, not the entire page. The researcher first proposes a mechanism, then clarifies requests rather than harm, then proposes a denominator. The AI raises selection and the researcher chooses a narrower protocol. The AI does not win an argument or dictate a specification. Explain the denominator issue in ordinary language: the set of situations being counted could itself change with treatment. Make clear that researcher turns are illustrative.')
frame(9,'Two agents checked the proposal');bullets(['The source reviewer checked the claim against the paper.','The methods reviewer examined the outcome, comparison and analysis.','They then read each other’s objections. One unresolved issue: a contact-prompt effect does not establish a bridging mechanism.'],gap=104);link(70,600,'Open the actual reports and cross-checks','/workshop/reviews.html');end('9:30–11:00. Open the actual reports. Show the source locators and the methods reviewer’s questions. Then show each cross-check at the end of its report. These are actual separate Codex agents used during revision. Multiple agents can share a mistake, so the source and substantive question remain the test. Point to one open researcher decision: who is the target population? Do not answer it on Christopher’s behalf.')
frame(10,'From the search to a written proposal');para(70,204,'An evidence assessment and proposed study, compiled on 9 September 2026.',1120,27);bullets(['8 September: agent-assisted search and nine-study evidence table.','9 September: source and methods agents review and cross-check.','9 September: revised proposal written and compiled in LaTeX.'],start=305,size=24,gap=70);para(70,520,'The skill codifies the earlier workflow. The coauthor dialogue is scripted.',1120,21);link(70,597,'Open the PDF','/artifacts/study-protocol.pdf');link(390,597,'Production record','/workshop/production.html');link(750,597,'LaTeX source','/artifacts/study-protocol.tex');end('Show when the artifact was made and what produced it. The search was on 8 September, independent reviews and original compilation on 9 September. The workshop skill was written after the search. The paired exchange is scripted, not a transcript of Christopher. Open the production record for links to the evidence, reviews and timestamped compilation record. The provenance note was added on 15 September; no fresh search is claimed. This remains a proposed study, not empirical findings.')
# A 15-minute route through all 17 slides, including opening evidence.
import re
durations=[30,15,15,15,65,65,35,45,40,40,40,35,75,80,55,100,150]
assert len(notes)==len(durations)==17
elapsed=0
for i,seconds in enumerate(durations):
 original=re.sub(r'^\d+:\d+–\d+:\d+(?:, then five minutes of discussion)?\.\s*','',notes[i])
 notes[i]=f'{elapsed//60}:{elapsed%60:02d}–{(elapsed+seconds)//60}:{(elapsed+seconds)%60:02d}. '+original
 elapsed+=seconds
assert elapsed==900
C.save()
Path('research/speaker-notes.md').write_text('# Presenter notes\n\n15-minute walkthrough, followed by five minutes of discussion. Pre-open the opening readings, workshop index, evidence table and protocol PDF. The four opening slides take four minutes; each archetype then gets forty seconds. Links in the slides open the private hosted copies; offline users should use the local workshop index.\n\n'+'\n\n'.join('## Slide '+str(i+1)+'\n\n'+n for i,n in enumerate(notes)))
P.joinpath('speaker-notes.md').write_text(Path('research/speaker-notes.md').read_text())
print('Created 17 PDF slides with direct links and timed notes.')
