from pathlib import Path
import json,html,shutil,zipfile
R=Path('research');P=Path('public/artifacts');W=Path('public/workshop')
for src,dst in [('protocol/memo.pdf','study-protocol.pdf'),('protocol/memo.tex','study-protocol.tex'),('workshop-howto.md','workshop-howto.md'),('audit/source-audit.md','source-audit.md'),('audit/methods-audit.md','methods-audit.md'),('audit/coauthor-dialogue.md','coauthor-dialogue.md'),('skills/literature-audit/SKILL.md','SKILL.md')]:shutil.copy2(R/src,P/dst)
# Standalone source uses its adjacent bibliography.
s=P.joinpath('study-protocol.tex').read_text().replace('\\bibliography{../references}','\\bibliography{references}');P.joinpath('study-protocol.tex').write_text(s)
with zipfile.ZipFile(P/'literature-audit.zip','w',zipfile.ZIP_DEFLATED) as z:z.write(R/'skills/literature-audit/SKILL.md','literature-audit/SKILL.md')
style='''body{font:18px/1.65 Arial,sans-serif;color:#222;background:#fff;margin:0}main{max-width:1100px;margin:auto;padding:30px 36px 70px}h1,h2{font-family:Georgia,serif;font-weight:normal}h1{font-size:34px}h2{font-size:25px;margin-top:32px}a{color:#493280;text-underline-offset:3px}nav{font-size:16px;border-bottom:1px solid #bbb;padding-bottom:18px}pre{white-space:pre-wrap;font:16px/1.6 Menlo,monospace;background:#f5f5f5;padding:20px;overflow-wrap:anywhere}small,.meta{font-size:15px;color:#666}table{border-collapse:collapse;width:100%;font-size:16px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #ccc;padding:12px 10px}th{background:#f4f3f5}input,select,button{font:inherit;padding:8px;border:1px solid #aaa;background:white;border-radius:0}button{cursor:pointer}button:focus-visible,a:focus-visible{outline:3px solid #bcb0d9}details{border-top:1px solid #ccc;padding:18px 0}summary{cursor:pointer;font-weight:bold}.dialogue p{max-width:820px;margin:24px 0}.dialogue b{display:block;font-size:15px;color:#555}.controls{display:flex;gap:18px;flex-wrap:wrap;margin:24px 0}.controls label{display:flex;flex-direction:column;font-size:16px}.record{border-top:1px solid #bbb;padding:24px 0}.record h2{margin:0 0 8px}.empty{padding:24px;border:1px solid #ccc}@media(max-width:700px){main{padding:20px}table{font-size:14px}th,td{padding:7px}.tablewrap{overflow-x:auto}}'''
W.joinpath('style.css').write_text(style)
def page(name,title,body,script=''):
 W.joinpath(name+'.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><link rel="stylesheet" href="style.css"><main><nav><a href="/workshop/index.html">Workshop files</a> &nbsp; / &nbsp; <a href="/artifacts/presentation.pdf">Slides PDF</a></nav><h1>'+title+'</h1>'+body+'</main>'+script+'</html>')
page('howto','Using a literature-review skill','''<p>This skill was written for this workshop. Download it, read the instructions, and put the folder in the project where you want to work.</p><p><a href="/artifacts/literature-audit.zip">Download literature-audit.zip</a> · <a href="/artifacts/SKILL.md">Open SKILL.md</a></p><h2>1. Put the skill in the project</h2><pre>Codex CLI / IDE:  .agents/skills/literature-audit/SKILL.md
Claude Code:      .claude/skills/literature-audit/SKILL.md</pre><p>These paths are relative to your research project. Restart the session if the new skill does not appear.</p><h2>2. Invoke it and give it an assignment</h2><pre>Codex CLI / IDE:  $literature-audit
Claude Code:      /literature-audit</pre><p>The file can also be attached directly with an explicit instruction to follow it. The host still needs search and file tools; a skill supplies instructions, not subscription access.</p><pre>Assess whether AI chatbots reduce requests for emotional support or personal advice to existing friends and family. Find 8–12 primary studies. Record queries and inclusion decisions. Check the actual instruments and source versions. Produce an evidence table and verified bibliography. Ask me about consequential ambiguities before drawing a conclusion.

Use separate source and methods reviewers. Have them cross-check each other's objections. Preserve disagreements and questions for me.</pre><h2>3. Open what it produced</h2><p><a href="evidence.html">Evidence table</a> · <a href="/artifacts/search-log.md">Search record</a> · <a href="reviews.html">Actual reviewer reports</a> · <a href="/artifacts/study-protocol.pdf">Compiled proposal</a></p><p class="meta">The original review predates this reusable skill. The reviewers were run during this revision. These files are not presented as the result of a recorded Claude Code session: the local Claude login had expired, and the installed Codex CLI executable was unavailable. The paired dialogue is scripted.</p><h2>Official documentation</h2><p><a href="https://learn.chatgpt.com/docs/build-skills">Codex: creating and loading skills</a> · <a href="https://code.claude.com/docs/en/skills">Claude Code: creating and invoking skills</a></p><p class="meta">Instructions checked 9 September 2026. This is a workshop-authored skill, not an official literature-review package.</p>''')
E=json.loads(R.joinpath('evidence.json').read_text())
rows=''.join('<tr><td><a href="'+html.escape(e['url'])+'">'+html.escape(e['short']+' ('+str(e['year'])+')')+'</a><br><small>'+html.escape(e['status'])+'</small></td>'+''.join('<td>'+html.escape(e[k])+'</td>' for k in ['design','outcome','limit'])+'</tr>' for e in E)
page('evidence','Evidence table','<p>Bounded scoping review, 8 September 2026. Nine records. This table distinguishes the outcome of interest from related measures.</p><p><a href="/artifacts/evidence.csv">Open CSV</a> · <a href="/artifacts/search-log.md">Search record</a> · <a href="/artifacts/retrieval-manifest.json">Retrieval record</a> · <a href="explorer.html">Explore full records</a></p><div class="tablewrap"><table><thead><tr><th>Study</th><th>Design</th><th>Outcome</th><th>Limit for this question</th></tr></thead><tbody>'+rows+'</tbody></table></div>')
D=R.joinpath('audit/coauthor-dialogue.md').read_text().split('\n\n')
body='<p class="meta">'+html.escape(D[1])+'</p><div class="dialogue">'
for t in D[2:]:
 role,txt=t.split(': ',1);body+='<p><b>'+html.escape(role)+'</b>'+html.escape(txt)+'</p>'
page('coauthor','Working through the argument',body+'</div><p><a href="reviews.html">Open the actual source and methods reviews</a> · <a href="/artifacts/study-protocol.pdf">Open the resulting proposal</a></p>')
body='<p>Two separate agents reviewed the existing research files, then read each other’s objections. Reports below are their actual output from 9 September 2026. Neither agent supplies empirical evidence, and neither has answered the questions on the researcher’s behalf.</p>'
for k,label in [('source','Source reviewer'),('methods','Methods reviewer')]:
 body+='<h2>'+label+'</h2><p><a href="/artifacts/'+k+'-audit.md">Open original report</a></p><pre>'+html.escape(R.joinpath('audit/'+k+'-audit.md').read_text())+'</pre>'
page('reviews','Source and methods review',body)
# Explicit classifications for this outcome, not machine inference.
classes={'fang2025':'social','guingrich2025':'social','chandra2025':'relationship','defreitas2025':'loneliness','meng2021':'support','meng2025':'support','young2024':'support','skjuve2021':'relationship','ueda2026':'professional'}
for e in E:e['category']=classes[e['key']]
body='''<p>Choose an outcome to see which records address it. Click a study to inspect the measure, source version and access limits.</p><div class="controls"><label>Outcome<select id="outcome"><option value="all">All nine records</option><option value="requests">Requests to friends and family</option><option value="loneliness">Loneliness relief</option><option value="social">Social health / socialization</option><option value="support">Support messages / evaluations</option><option value="relationship">Chatbot relationships / experience</option><option value="professional">Professional help attitudes</option></select></label><label>Search within the records<input id="query" type="search" placeholder="Author, measure or design"></label><label>Access<select id="access"><option value="all">All access levels</option><option value="full">Full text assessed</option><option value="abstract">Abstract / metadata only</option></select></label></div><p id="count" aria-live="polite"></p><div id="records"></div><p class="meta">The classifications are from this bounded review. An empty category means that no record in this set directly operationalizes that outcome; it does not establish a gap in the entire literature. Filters do not call an AI service.</p>'''
script='<script>const evidence='+json.dumps(E).replace('<','\\u003c')+''';const out=document.querySelector('#records');function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n}function render(){const cat=document.querySelector('#outcome').value,q=document.querySelector('#query').value.toLowerCase(),access=document.querySelector('#access').value;const rows=evidence.filter(e=>(cat==='all'||e.category===cat)&&JSON.stringify(e).toLowerCase().includes(q)&&(access==='all'||(access==='full'?e.access.toLowerCase().includes('full'):!e.access.toLowerCase().includes('full'))));out.replaceChildren();document.querySelector('#count').textContent=rows.length+' of 9 records';if(!rows.length){const p=node('p',cat==='requests'?'None of these records directly counts requests for informal support from friends and family. Reset the outcome to see the adjacent evidence.':'No records match these filters.');p.className='empty';out.append(p)}rows.forEach(e=>{const d=document.createElement('details');d.append(node('summary',e.short+' ('+e.year+') — '+e.title));[['Design',e.design],['Measured outcome',e.outcome],['Finding',e.finding],['Limit',e.limit],['Source location',e.locator],['Publication status',e.status],['Access',e.access]].forEach(([a,b])=>d.append(node('p',a+': '+b)));const a=node('a','Open the primary source');a.href=e.url;d.append(a);out.append(d)})}document.querySelectorAll('select,input').forEach(e=>e.addEventListener('input',render));render();</script>'''
page('explorer','Explore the review records',body,script)
print('Created direct-open workshop files, skill archive and evidence explorer.')
